config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  devise_scope :user do
    authenticated :user do
      root 'tools#index', as: :authenticated_root
    end

    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end

  get 'dashboard', to: "pages#index", as: :dashboard
  get 'mylisting', to: "pages#show", as: :mylisting
  get 'home', to: "pages#home", as: :homepage

  resources :tools do
    resources :bookings
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :tool
  validates :start_date, :end_date, presence: true
end

app/models/tool.rb
class Tool < ApplicationRecord
  belongs_to :user
  validates :user, presence: true
  validates :condition, presence: true, inclusion: { in: %w(Mint Excellent Good Fair  Poor) }
  has_many :bookings, dependent: :destroy
  has_one_attached :image
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :tools, dependent: :destroy
  has_many :bookings, dependent: :destroy
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :address, :phone_number])

    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name, :address, :phone_number])
  end

  def after_sign_in_path_for(resource)
    tools_path(current_user)
  end

  def after_sign_up_path_for(resource)
    tools_path(current_user)
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController

  def new
    @booking = Booking.new
    @booking.tool_id = @tool
    @booking.status = "Available"
  end

  def create
    @tool = Tool.find(params[:tool_id])
    @tool_id = params[:tool_id]
    @booking = Booking.new(booking_params)
    if (@booking.end_date == nil || @booking.start_date == nil)
      redirect_to tool_path(@tool), notice: "Please enter dates"
    else
      if !(Tool.find(@tool_id).user_id == current_user.id)
        @booking.price = (@booking.end_date - @booking.start_date) * @tool.rate
        @booking.status = "Booked"
        @booking.tool_id = @tool_id
        @booking.user = current_user
        if @booking.save
          redirect_to tool_booking_path(@tool_id, @booking.id), notice: 'Succesful booking!'
        else
          render :new
        end
      else
        redirect_to tool_path(@tool_id), notice: "You can't book your own Tool mate!"
      end
    end
  end

  def show
    @booking = Booking.find(params[:id])
    @tool = Tool.find(params[:tool_id])
    @user = User.find(@tool.user_id)
  end

  def update
    if @booking.update(booking_params)
        redirect_to @booking, notice: 'Change request updated!'
      else
        render :edit
      end
  end

  private

  def booking_params
    params.require(:booking).permit(:start_date, :end_date)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def home
  end

  def index
    @user = current_user
    # booking on other tool
    @booking = Booking.where(user_id:@user.id)
    @tools = Tool.where(user_id:@user.id)
    @lent = Booking.where.not(user_id:@user.id)
    @day = Date.today
  end

  def show
    @user = current_user
    @tools = Tool.where(user_id:@user.id)
  end
end

app/controllers/tools_controller.rb
class ToolsController < ApplicationController
  before_action :set_tool, only: [:show, :edit, :update, :destroy]

  def index
    @tools = Tool.where.not(user_id: current_user.id)
    if params[:query].present?
      @tools = @tools.where("name ILIKE ?", "%#{params[:query]}%")
    end
  end

  def new
    @tool = Tool.new

  end

  def create
    @tool = Tool.new(tool_params)
    @tool.user = current_user
    if @tool.save
      redirect_to tools_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show

    @booking = Booking.new
    @user = User.find(@tool.user_id)
    # raise
    @markers ={
      lat: @user.latitude,
      lng: @user.longitude
    }
  end

  def edit
  end

  def update
    if @tool.update(tool_params)
      redirect_to tool_path(@tool)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @tool.destroy
    redirect_to mylisting_path, status: :see_other
  end

  private

  def set_tool
    @tool = Tool.find(params[:id])
  end

  def tool_params
    params.require(:tool).permit(:name, :description, :rate, :condition, :image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/_form.html.erb
<div class="container">
<%# image here %>
  <div class="row" d-flex>
    <div data-controller="booking-price" data-booking-price-price-value="<%= @tool.rate %>" class="mt-5 border p-3 rounded">
      <!-- Displays price/night on top of form -->
      <p class='fw-bold fs-3'>Rate: $<%= @tool.rate%> <small class='fw-light'>/day</small></p>
      <%= simple_form_for [@tool, @booking] do |f| %>
        <!-- On change of dates, it triggers our update inside of our JS controller -->
        <%= f.input :start_date, html5: true, input_html: { data: { booking_price_target: 'start_date', action: 'change->booking-price#update' }, min: Date.today } %>
        <%= f.input :end_date, html5: true, input_html: { data: { booking_price_target: 'end_date', action: 'change->booking-price#update' }, min: Date.today } %>
        <%= f.submit 'Book the Item', class: 'booking-btn' %>
        <!-- Hidden when no dates chosen, total amount displayed here when changed -->
        <p class='mt-3 d-flex align-items-center justify-content-between'>
          <span data-booking-price-target='info'></span>
          <span class='fw-bold' data-booking-price-target='price'></span>
        </p>
      <% end %>
    </div>
  </div>
</div>

app/views/bookings/edit.html.erb
<%= render 'form' %>

app/views/bookings/new.html.erb
<%= render 'form' %>

app/views/bookings/show.html.erb
<div class="container">
  <div class="row" style="justify-content:center;">
    <div class="col-8 mt-5" style="border: ridge;
    padding: 31px;">
      <div class="booking-title d-flex">
        <i class="fa-solid fa-circle-check"></i>
        <h3> Booking confirmed</h3>
      </div>
      <div class="bookingall d-flex">
        <div class="booking-description col-6">
          <h2>Details</h2>
          <p><strong> Booking reference: <%= @booking.tool_id %></strong></p>
          <p> Item: <%= @tool.name %></p>
          <p> Booking Date: <%= @booking.start_date %> to <%= @booking.end_date %></p>
          <p> Total Price: $<%= @booking.price %></p>
        </div>
        <div class="booking-rental col-6">
          <h2>Item collection:</h2>
          <p> Name: <%= @user.first_name %>  <%= @user.last_name %></p>
          <p> Address:  <%= @user.address %></p>
          <p> Phone number:  <%= @user.phone_number %></p>
        </div>
      </div>
      <div class="bookingconfirm-btn">
        <%=link_to "View Booking",  dashboard_path, class: "btn btn-flat update" %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rent</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
    <link href="https://api.mapbox.com/mapbox-gl-js/v2.11.0/mapbox-gl.css" rel="stylesheet">
  </head>

  <body>
    <%= render "shared/flashes" %>
    <%= render "shared/navbar" %>
    <%= yield %>

    <script src="https://cdn.jsdelivr.net/npm/flatpickr"></script>
  </body>
</html>

app/views/pages/_currentrent.html.erb
<div class="booking-card">
  <div class="row" id="dash-card">

      <% @booking.each do |t| %>
        <div class="card">
          <div class="tool-row d-flex" style="justify-content: space-around;">
            <div class="dash-item">
              <h3>Item</h3>
              <p><%= t.tool.name %><p>
              <p><%= t.tool_id %></p>
            </div>
            <div class="dash-bookid ml-3">
              <h3>Booking Id</h3>
              <p><%= t.id %></p>
            </div>
            <div class="dash-bookid ml-3">
              <h3>Lender</h3>
              <% @user = User.find(Tool.find(t.tool_id).user_id)%>
              <p><%= @user.first_name %> <%= @user.last_name %></p>
            </div>
            <div class="dash-bookdate">
              <h3>Booking Date</h3>
              <p><%= t.start_date %>-<%= t.end_date %></p>
            </div>
            <div class="dash-status">
              <h3>Status</h3>
              <p><%=t.status%></p>
            </div>
            <div class="dash-price">
              <h3>Price</h3>
              <p>$<%= t.price %></p>
            </div>
            <%=link_to "View Item",  tool_booking_path(t.tool_id, t.id), class: "btn btn-flat" %>
          </div>
        </div>
      <% end %>
  </div>
</div>

app/views/pages/_myitemrental.html.erb
<div class="rental-card">
  <div class="row">
    <% @lent.each do |booking| %>
      <% if Tool.find(booking.tool_id).user_id == current_user.id %>
        <% @tool = Tool.find(booking.tool_id)%>
          <div class="card">
            <div class="tool-row d-flex" style="justify-content: space-around;">
              <div class="dash-item">
                <h3>Item</h3>
                <p><%= @tool.name %><p>
              </div>
              <div class="dash-bookdate">
                <h3>Booking Date</h3>
                <p><%=booking.start_date %> - <%= booking.end_date %></p>
              </div>
              <div class="dash-bookdate">
                <h3>Borrower</h3>
                <% @user = User.find(booking.user_id) %>
                <p> <%= @user.first_name %> <%= @user.last_name %></p>
              </div>
              <div class="dash-status">
                <h3>Status</h3>
                <p><%= booking.status %></p>
              </div>
              <div class="dash-price">
                <h3>Price</h3>
                <p>$ <%= booking.price %></p>
              </div>
            </div>
          </div>
      <% end %>
    <% end %>
  </div>
</div>

app/views/pages/home.html.erb
<%# hero %>
<div class="container">
  <div class="banner">
    <div class="col-md-6 info">
      <h1 style="color: #black">RENT tools <br><strong>from people in your area</strong></h1>
      <div class="banner-subheading"
        style="color: #black">for your upcoming DIY projects
      </div>

      <div class="btn-wrapper">
        <div class="banner-button">
          <a href="" target="_blank" class="btn btn-secondary " style="color: black">Sign Up </a>
        </div>
      </div>
    </div>
  </div>
<%# card %>

  <div class="second-call">
    <div class="card-home-one">
      <h3>TOOL OWNERS</h3>
    <p>Do you have spare tools & equipment sitting around in your garage, doing nothing? (Remember how much you paid for them?)</p>
    </div>
    <div class="card-home-two">
      <h3>TOOL RENTERS</h3>
      <p>Have a project, but not the tools? (And don’t want to deal with the clutter, hassle, & expense of buying them?)</p>
    </div>
  </div>
</div>


<%# search button %>

<div class="row justify-content-center">
  <div class="col-sm-8 my-3">
    <%= form_with url: tools_path, method: :get, class: "d-flex" do %>
      <%= text_field_tag :query,
            params[:query],
            class: "form-control",
            placeholder: "Type a keyword"
        %>
      <%= submit_tag "Search", name: "", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/pages/index.html.erb
<div class="container-fluid mt-5">

  <div class="row">
    <div class="col-3 sm-3" id="dashboard-profile">
      <div class="row">
        <div class="profile-dash p-5">

          <%= image_tag @user.image_url %>
        </div>
        <div class="profile pt-5">
        <h3><%= @user.first_name %> <%= @user.last_name  %></h3>
        <p><%= @user.email %></p>
        <p><%= @user.phone_number %></p>
        <p><%= @user.address %></p>
        <p class="profile-link"><%=link_to "My Listing",  mylisting_path, class: "dash-listing" %></p>
        </div>
      </div>
    </div>

    <div class="col-8 sm-6" id="dashboard-bigcard">
      <div class="top-dash d-flex" style="justify-content: space-between;">
        <div class="topdash-left">
          <h2>Hello, <%= @user.first_name %></h2>
          <h3>Today is <%= @day %>
        </div>
        <div class="topdash-right">
          <%=link_to "Add Listing",  new_tool_path, class: "btn btn-flat" %>
        </div>
      </div>

      <div class="row">
        <div class="card" style="width: 31rem;" id="total-listing">
          <h3>TOTAL LISTING</h3>
          <p><%= @tools.length %> items </p>
        </div>
        <div class="card" style="width: 31rem;" id="total-booking">
          <h3>WHAT I EARNED</h3>
          <% total_value = 0 %>
          <% @lent.each do |booking| %>
            <% if Tool.find(booking.tool_id).user_id == current_user.id %>
                <% total_value += booking.price %>
            <% end %>
          <% end %>
          <p><strong>$ <%= total_value %></strong></p>
      </div>

<%# BOOKING INFORMATION %>
      <div class="booking-tab">
        <div
          data-controller="tabs"
          data-tabs-active-class="activetab"
          data-tabs-default-tab-value="tab1">

          <!-- buttons to toggle between tabs -->
          <div class="flex">
            <button id="tab1" data-tabs-target="btn" data-action="click->tabs#select">Borrowed Items</button>
            <button id="tab2" data-tabs-target="btn" data-action="click->tabs#select">Lent Items</button>
          </div>

          <!-- the tabs -->
          <div class="tab-body">
            <div data-tabs-target="tab" id="tab1">
              <%= render 'currentrent' %>
            </div>

            <!-- tab 2 is hidden by default, to prevent 'flashing in' -->
            <div data-tabs-target="tab" id="tab2" class='hidden'>
              <%= render 'myitemrental' %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/pages/show.html.erb
<div class="container">
  <div class="listing-card">
    <h2>Your Listing</h2>
    <h2><%= @tools.length %> item in total</h2>
    <div class="row " id="tool_listing">
      <% @tools.each do |t| %>
      <div class="card">
        <div class="tool-row d-flex" style="text-align:center;" >
          <div class="mylisting-img">
            <%= cl_image_tag t.image.key, height: 200, width:200,
             crop: :scale %>
          </div>
          <div class="mylist-description ml-3" style="text-align:left;">
            <h4><%= t.name %></h4>
            <%=link_to "View",  tool_path(t.id), class: "btn btn-flat" %>
            <%=link_to "Update",  edit_tool_path(t.id), class: "btn btn-flat update" %>
          </div>
          <%= link_to icon('fa-solid fa-trash', class:'fa-shake'), tool_path(t.id), data: { turbo_method: :delete, turbo_confirm: "Are you sure you want to delete this tool?" } %>
        </div>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to tools_path, class: "navbar-brand" do %>
      <%= image_tag asset_path('rentlogo.png') %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item active" style="color:#3f6487; font-weight: 600;">
            <%= link_to "New Listing", new_tool_path, class: "nav-link"%>
          </li>
          <li class="nav-item">
            <%= link_to "My Listings", mylisting_path, class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
          <div class="avatar" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <%= image_tag current_user.image_url , class: "avatar", alt: "dropdown menu" %>
          </div>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Dashboard", dashboard_path, class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/tools/_form.html.erb
<%= simple_form_for(tool) do |f| %>
  <%= f.input :name %>
  <%= f.input :description %>
  <%= f.input :rate, input_html: { placeholder: '$' } %>
  <%= f.input :condition, collection: %w(Mint Excellent Good Fair Poor)%>
  <%= f.input :image, as: :file, label: 'Upload' %>

  <%= f.submit class: "btn btn-primary" %>
  
<% end %>

app/views/tools/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to tools_path, class: "navbar-brand" do %>
      <%= image_tag asset_path('rentlogo.png') %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <li class="nav-item active">
          <%= link_to "List an item", new_tool_path, class: "nav-link" %>
        </li>
      </ul>
    </div>
  </div>
</div>

app/views/tools/edit.html.erb
<div class="container mt-4">
  <div class="row">
    <div class="col-6 m-auto">
      <div class="flat-form">
        <h1>Edit Tool</h1>
        <div class="mt-3">
          <%= render "form", tool: @tool %>
        </div>
        <div class="mt-3">
          <%= link_to "Cancel", mylisting_path %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/tools/index.html.erb
<div class="container-fluid mt-5">
  <div class="row-tool">
    <div class="col-10" id="tool-category">
      <h1>Home Improvement Tools</h1>
    </div>
    <div class="col-sm-4 my-3">
      <%= form_with url: tools_path, method: :get, class: "tool-form d-flex" do %>
        <%= text_field_tag :query,
              params[:query],
              class: "form-control",
              placeholder: "Look for something specific?"
          %>
        <%= submit_tag "Search", name: "", class: "btn search-btn" %>
      <% end %>
    </div>

    <div class="col-12 mt-5">
      <h3><%= @tools.length %> items found </h3>
      <div class="tool-maincard">
        <% @tools.each do|b| %>
          <div class="tool-card" >
              <%= cl_image_tag b.image.key, height: 400, width: 400, crop: :scale %>
              <div class="tool-card-body">
                <h3><strong><%= link_to b.name, tool_path(b.id) %></strong></h3>
                <h4>$<%= b.rate %>/day</h4>
              </div>
            </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/tools/new.html.erb
<div class="container mt-4">
  <div class="row">
    <div class="col-6 m-auto">
      <div class="flat-form">
        <h1>Rent out your unused item today! </h1>
        <div class="mt-3">
          <%= render "form", tool: @tool %>
        </div>
        <div class="mt-3">
          <%= link_to "Cancel", tools_path %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/tools/show.html.erb
<%# list of movie with overview and rating %>
<div class="container mt-12 d-flex">
  <div class="col-8">
    <div class="show-img"><%= image_tag(@tool.image)%></div>
    <div class="card-body">
      <h3>Description</h3>
      <p> <%= @tool.description %></p>
      <p><strong>Condition:</strong> <%= @tool.condition %></p>
      <h5>Location</h5>

      <div style="width: 100%; height: 300px;"
        data-controller="map"
        data-map-markers-value="<%= @markers.to_json %>"
        data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
      </div>
    </div>
  </div>

  <div class="col-4 pt-5" id="showpage" >
    <h3 class="tool-show"><%= @tool.name %></h3>
    <div class="showcard d-flex" style="justify-content:space-between;">
      <p>Item by <%= @tool.user.first_name %>
      <p><i class="fa-solid fa-star" style="color: #e6d72d;"></i> <%= @tool.rating %></p>
    </div>

    <div class="tool-rate">Daily Rate
      <p><strong>$<%= @tool.rate %></strong> /day</p>
    </div>
    <div data-controller="toggle" class="mt-5">
      <button data-action="click->toggle#fire" class="showtoolbtn">Price and Availability</button>
      <div data-toggle-target="togglableElement" class="d-none">
        <%= render "bookings/form", tool: @tool, booking: @booking %>
      </div>
    </div>
  </div>

</div>